sudo: required
services:
  - docker

before_install:
  - docker build -t gulshanss/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gulshanss/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-891377056438"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
